{
    'name' : 'Real State Property',
    'version' : '17.0',
    'author' : 'Nicolas G. Tafle',
    'license' : 'LGPL-3',
    'depends' : ['base', 'contacts'],
    'data' : [
        'security/ir.model.access.csv',
        'views/real_state_action.xml',
        'views/state_property_type_action.xml',
        'views/state_property_tag_action.xml',
        'views/real_state_menu.xml',
        'views/real_state_form.xml',
        'views/real_state_tree.xml',
        'views/state_property_type_views.xml',
        'views/state_property_tag_views.xml',
        'views/state_property_offer_views.xml',
    ],
    'application' : True,
}